// src/routes/Footer.svelte
<footer class="text-center text-sm">
	<span>KMA Tín Chỉ v2022.12 - ngosangns</span>
</footer>

<style>
	footer {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		padding: 12px;
		width: 100%;
		min-width: 60rem;
	}

	@media (min-width: 480px) {
		footer {
			padding: 12px 0;
		}
	}
</style>

// src/components/Footer.vue
<template>
    <footer class="text-center text-sm">
        <span>KMA Tín Chỉ v2022.12 - ngosangns</span>
    </footer>
</template>

<style>
	footer {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		padding: 12px;
		width: 100%;
		min-width: 60rem;
	}

	@media (min-width: 480px) {
		footer {
			padding: 12px 0;
		}
	}
</style>
