// src/routes/SessionBar.svelte
<tr>
	<th colspan="2" class="text-center bg-base-200">
		<div class="grid grid-cols-2 grid-rows-2">
			<span />
			<span>Tiết</span>
			<span>Thứ</span>
			<span />
		</div>
		<div
			class="relative border-base-content border-b w-full"
			style="transform: skewY(30deg) translateY(-1.1rem) translateX(.1rem) scaleX(.30)"
		/>
	</th>
	<th class="text-center bg-base-200">1</th>
	<th class="text-center bg-base-200">2</th>
	<th class="text-center bg-base-200">3</th>
	<th class="text-center bg-base-200">4</th>
	<th class="text-center bg-base-200">5</th>
	<th class="text-center bg-base-200">6</th>
	<th class="text-center text-base-100 bg-neutral">7</th>
	<th class="text-center text-base-100 bg-neutral">8</th>
	<th class="text-center text-base-100 bg-neutral">9</th>
	<th class="text-center text-base-100 bg-neutral">10</th>
	<th class="text-center text-base-100 bg-neutral">11</th>
	<th class="text-center text-base-100 bg-neutral">12</th>
	<th class="text-center text-base-100 bg-neutral-focus">13</th>
	<th class="text-center text-base-100 bg-neutral-focus">14</th>
	<th class="text-center text-base-100 bg-neutral-focus">15</th>
	<th class="text-center text-base-100 bg-neutral-focus">16</th>
</tr>

// src/components/SessionBar.vue
<template>
    <tr>
        <th colspan="2" class="text-center bg-base-200">
            <div class="grid grid-cols-2 grid-rows-2">
                <span />
                <span>Tiết</span>
                <span>Thứ</span>
                <span />
            </div>
            <div
                class="relative border-base-content border-b w-full"
                style="transform: skewY(30deg) translateY(-1.1rem) translateX(.1rem) scaleX(.30)"
            />
        </th>
        <th class="text-center bg-base-200">1</th>
        <th class="text-center bg-base-200">2</th>
        <th class="text-center bg-base-200">3</th>
        <th class="text-center bg-base-200">4</th>
        <th class="text-center bg-base-200">5</th>
        <th class="text-center bg-base-200">6</th>
        <th class="text-center text-base-100 bg-neutral">7</th>
        <th class="text-center text-base-100 bg-neutral">8</th>
        <th class="text-center text-base-100 bg-neutral">9</th>
        <th class="text-center text-base-100 bg-neutral">10</th>
        <th class="text-center text-base-100 bg-neutral">11</th>
        <th class="text-center text-base-100 bg-neutral">12</th>
        <th class="text-center text-base-100 bg-neutral-focus">13</th>
        <th class="text-center text-base-100 bg-neutral-focus">14</th>
        <th class="text-center text-base-100 bg-neutral-focus">15</th>
        <th class="text-center text-base-100 bg-neutral-focus">16</th>
    </tr>
</template>
